### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wodim** [joneame/joneame#9]
Sin un orden particular:

- [x] Cargarse el código de geo,

- [ ] nubes,

- [x] detección del navegador (navegador.php)

- [ ] Eliminar los cortos

- [ ] Revisar creación de cuentas con Facebook, Twitter, etc (a lo mejor convendría rehacerlo, pero de momento es código muerto y conviene eliminarlo)  

- [ ] Pasar todo lo que sea posible al sistema de plantillas. Lo de ayuda.php es para echarse a llorar

- [x] Eliminar códigos de integración con servicios muertos (thumbnails en enlaces y vídeos embebidos en notitas)

- [ ] Mirar si aún funciona el sistema de trackbacks, o quizá eliminarlo por completo

- [ ] Todo el código "vasquizado" habría que traducirlo y limpiarlo

- [x] Pasar la coti a json. Eliminar la coti telnet

- [ ] Hay cosas que están duplicadas en vistas y en ajax. Por ejemplo, el textbox de añadir comentarios

- [ ] Actualizar jquery y fancybox

- [ ] Implementar una protección de hotlinking real (block.php) o eliminarla

- [ ] Detectar enlaces muertos y pasarlos por archive.org; cargarse el sistema de broken_link.php

- [ ] Mejorar el sistema de sphinx. Al menos que se puedan usar operadores de búsqueda, los cuales en teoría deberían funcionar

- [ ] Adecentar el sistema de internacionalización o eliminarlo

- [ ] Revisar sistema de clones: las fancyboxes siempre se generan mal

- [ ] Hay que darle una vuelta al sistema de encuestas. Hacerlo similar en diseño al de vbulletin 

- [x] La integración de jabber se fue para no volver pero aún hay vestigios por aquí y por allí

- [ ] Arreglar las queries mierders de notitas

- [ ] y de encuestas

- [ ] Arreglar o eliminar el código de las microcotillonas

- [ ] Los RSS suelen no tener enlace de vuelta a jonéame

- [ ] Investigar si se pueden cambiar algunos smileys por emojis

- [ ] Permitir el registro de usuarios sin poner un correo

- [ ] Las subidas de avataras han de ir a mayor calidad y resolución a partir de ahora

- [ ] Restaurar el backup de la jiskobox

- [ ] Hay que pensar en cambiar los iconos por algo vectorial

- [ ] Las notitas no tienen paginación

- [ ] Algo que sea como markdown

- [ ] Arreglar el problema de caché al cambiar de avatar

- [ ] Verificar si la generación de miniaturas usa opengraph

- [ ] Arreglar los cortos especiales (no se pueden desactivar)

- [ ] La tabla sneakers nunca se limpia tras 4a3459c y relacionados

**Comment by wodim** [comment]
Parte de jabber quitada en https://github.com/joneame/joneame/commit/b42274b2edcbe0b8ed2a5e6f1199e305afeb836f pero falta la parte de la cotillona en sí (esperaré a cuando la pase a json)

**Comment by wodim** [comment]
Cotillona en json en https://github.com/joneame/joneame/commit/4a3459c6cd926697e55be3c217e5210669ef010b

**Comment by wodim** [comment]
navegador.php https://github.com/joneame/joneame/commit/d50528d63ed144a79d6e59073de7abc365cc7fdd

**Comment by wodim** [comment]
sistemas viejos de vídeo en https://github.com/joneame/joneame/commit/824e0755d0a8ea033af0502d0f8b7b6de5d9ae90

**Comment by wodim** [comment]
ahora toda la ayuda está en plantillas https://github.com/joneame/joneame/commit/e164aa9eb2a018c5ff4ce92632aaecea0c31831c https://github.com/joneame/joneame/commit/3b69cb5760fdfaa79b95040345372783e33a081c

**Comment by wodim** [comment]
el código de geo se fue en https://github.com/joneame/joneame/commit/47ce1ffbe313b0478a3793ea53e4f8dd0fadcc28
